apiVersion: v1
kind: Service
metadata:
  name: collector-np
  namespace: voltron
  labels:
    app: collector
spec:
  ports:
    - name: 5000-tcp
      port: 5000
      nodePort: 30555
      targetPort: 5000
  type: NodePort
  selector:
    app: collector
